"""
phase_i.render_sample_snapshot — write a deterministic sample of the
context graph to disk for review.

Outputs:
    /home/ubuntu/investwise/phase_i/samples/graph_summary.md
    /home/ubuntu/investwise/phase_i/samples/graph_snapshot.json
    /home/ubuntu/investwise/phase_i/samples/edges_owned_by.md
    /home/ubuntu/investwise/phase_i/samples/edges_shariah.md

No wall-clock state — every run produces identical output for the
same data-layer reference state. Output goes to disk only, never stdout.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Iterable, List

from phase_i import build_graph, graph_snapshot, graph_summary, GraphEdge

SAMPLE_DIR = os.path.join(os.path.dirname(__file__), "samples")


def _edge_table(edges: Iterable[GraphEdge]) -> str:
    rows = ["| from | relation | to | truth | tier | source_document | confidence | as_of | review |",
            "|------|----------|----|-------|------|-----------------|------------|-------|--------|"]
    for e in sorted(edges, key=lambda x: (x.from_id, x.to_id)):
        rows.append(
            f"| {e.from_id} | {e.relation} | {e.to_id} | {e.truth_type} | "
            f"T{e.provenance_tier} | `{e.source_document_id}` | {e.confidence:.2f} | "
            f"{e.as_of_date} | {e.review_status} |"
        )
    return "\n".join(rows)


def render() -> None:
    os.makedirs(SAMPLE_DIR, exist_ok=True)
    g = build_graph()
    summary = graph_summary()
    snapshot = graph_snapshot()

    # graph_summary.md
    lines: List[str] = []
    lines.append("# Phase I — Context Graph Summary\n")
    lines.append(f"**Version:** `phase_i.{snapshot['phase_i_version']}`")
    lines.append(f"**Built from hash:** `{summary['built_from_hash']}`")
    lines.append(f"**Nodes:** {summary['node_count']}  ·  **Edges:** {summary['edge_count']}\n")
    lines.append("## Nodes by kind\n")
    lines.append("| kind | count |\n|------|------:|")
    for k, v in sorted(summary["nodes_by_kind"].items()):
        lines.append(f"| {k} | {v} |")
    lines.append("\n## Edges by relation\n")
    lines.append("| relation | count |\n|----------|------:|")
    for k, v in sorted(summary["edges_by_relation"].items()):
        lines.append(f"| {k} | {v} |")
    lines.append("\n## Edges by truth_type\n")
    lines.append("| truth_type | count |\n|------------|------:|")
    for k, v in sorted(summary["edges_by_truth"].items()):
        lines.append(f"| {k} | {v} |")
    lines.append("\n## Edges by provenance tier\n")
    lines.append("| tier | count |\n|------|------:|")
    for k, v in sorted(summary["edges_by_tier"].items()):
        lines.append(f"| T{k} | {v} |")
    lines.append("\n## Edges by review_status\n")
    lines.append("| review_status | count |\n|---------------|------:|")
    for k, v in sorted(summary["edges_by_review"].items()):
        lines.append(f"| {k} | {v} |")
    lines.append("\n*Generated by `phase_i.render_sample_snapshot`. Deterministic — no wall-clock state.*\n")
    with open(os.path.join(SAMPLE_DIR, "graph_summary.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    # graph_snapshot.json (deterministic)
    with open(os.path.join(SAMPLE_DIR, "graph_snapshot.json"), "w", encoding="utf-8") as fh:
        fh.write(json.dumps(snapshot, indent=2, ensure_ascii=False, sort_keys=True))

    # owned_by edges
    owned = [e for e in g.edges if e.relation == "owned_by"]
    with open(os.path.join(SAMPLE_DIR, "edges_owned_by.md"), "w", encoding="utf-8") as fh:
        fh.write(f"# Owned-By Edges ({len(owned)})\n\n" + _edge_table(owned) + "\n")

    # shariah edges
    shariah = [e for e in g.edges if e.relation == "shariah_compliant_per"]
    with open(os.path.join(SAMPLE_DIR, "edges_shariah.md"), "w", encoding="utf-8") as fh:
        fh.write(f"# Shariah-Compliance Edges ({len(shariah)})\n\n" + _edge_table(shariah) + "\n")

    print(f"Wrote 4 sample files to {SAMPLE_DIR}")
    print(f"  graph_summary.md   ({summary['node_count']} nodes, {summary['edge_count']} edges)")
    print(f"  graph_snapshot.json")
    print(f"  edges_owned_by.md  ({len(owned)} edges)")
    print(f"  edges_shariah.md   ({len(shariah)} edges)")


if __name__ == "__main__":
    render()
    sys.exit(0)
