"""
core.data_layer.ingestion.runners.sample_render — produce 4 sample
enriched institutional metadata outputs.

The four exemplars cover the audit-critical archetypes:
    1. Saudi bank          → TADAWUL:1180 (Saudi National Bank)
    2. UAE utility         → DFM:DEWA (Dubai Electricity & Water)
    3. GCC industrial      → TADAWUL:2010 (SABIC)
    4. Shariah-compliant   → TADAWUL:1120 (Al Rajhi Bank)

Renders both a human-readable markdown card and a JSON payload, side by
side, so reviewers can compare the rendered surface with the underlying
provenance contract. Outputs land under:

    core/data_layer/ingestion/samples/<archetype>.md
    core/data_layer/ingestion/samples/<archetype>.json
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any, Dict, List

from ...gcc_metadata import (
    GCC_METADATA, SCHEMA_FIELDS, get_gcc_metadata, provenance_summary, provenance_tier,
)


SAMPLE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(__file__)), "samples",
)


_ARCHETYPES = [
    ("01_saudi_bank",        "TADAWUL:1180", "Saudi National Bank"),
    ("02_uae_utility",       "DFM:DEWA",     "Dubai Electricity & Water Authority"),
    ("03_gcc_industrial",    "TADAWUL:2010", "SABIC"),
    ("04_shariah_compliant", "TADAWUL:1120", "Al Rajhi Bank"),
]


def _fmt_field(name: str, field: Dict[str, Any]) -> str:
    if not isinstance(field, dict):
        return f"| {name} | {field} | — | — | — |"
    val = field.get("value")
    if val is None:
        val_str = "*missing*"
    else:
        val_str = str(val)
    dq = field.get("data_quality", "missing")
    st = field.get("source_type", "missing")
    conf = field.get("confidence", 0.0)
    tier = provenance_tier(field)
    as_of = field.get("as_of_date") or "—"
    return f"| {name} | {val_str} | T{tier} {dq} | {st} | conf={conf:.2f} · {as_of} |"


def render_markdown(label: str, ticker: str, display_name: str) -> str:
    entry = get_gcc_metadata(ticker)
    ps = provenance_summary(entry)
    head = (
        f"# {display_name} ({ticker})\n\n"
        f"**Archetype:** `{label}`  ·  **Source:** {entry.get('source', 'unknown')}  ·  "
        f"**Tier-1 fields:** {ps['tier_1']}  ·  **Missing fields:** {ps['missing']}\n\n"
        f"## Provenance summary\n\n"
        f"| verified | derived | estimated | missing | fallback_used |\n"
        f"|---|---|---|---|---|\n"
        f"| {ps['verified']} | {ps['derived']} | {ps['estimated']} | {ps['missing']} | {ps['fallback_used']} |\n\n"
        f"| Tier 1 (issuer/exchange/regulator) | Tier 2 (derived) | Tier 3 (estimated) | Tier 4 (missing) |\n"
        f"|---|---|---|---|\n"
        f"| {ps['tier_1']} | {ps['tier_2']} | {ps['tier_3']} | {ps['tier_4']} |\n\n"
        f"## Field-level provenance\n\n"
        f"| field | value | tier · quality | source_type | confidence · as_of |\n"
        f"|---|---|---|---|---|\n"
    )
    rows = [_fmt_field(name, entry.get(name)) for name in SCHEMA_FIELDS]
    body_notes = entry.get("notes", "")
    notes_block = f"\n## Notes\n\n{body_notes}\n" if body_notes else ""
    return head + "\n".join(rows) + "\n" + notes_block


def render_json(label: str, ticker: str, display_name: str) -> str:
    entry = get_gcc_metadata(ticker)
    ps = provenance_summary(entry)
    return json.dumps({
        "archetype": label,
        "display_name": display_name,
        "ticker": ticker,
        "provenance_summary": ps,
        "entry": entry,
    }, indent=2, ensure_ascii=False, sort_keys=True)


def main() -> int:
    os.makedirs(SAMPLE_DIR, exist_ok=True)
    summary_lines: List[str] = []
    summary_lines.append("# GCC Metadata Sample Renders\n")
    summary_lines.append(f"Source directory: `{SAMPLE_DIR}`\n")
    summary_lines.append("Generated by `core.data_layer.ingestion.runners.sample_render`.\n")
    summary_lines.append("")
    for label, ticker, name in _ARCHETYPES:
        md = render_markdown(label, ticker, name)
        js = render_json(label, ticker, name)
        md_path = os.path.join(SAMPLE_DIR, f"{label}.md")
        js_path = os.path.join(SAMPLE_DIR, f"{label}.json")
        with open(md_path, "w", encoding="utf-8") as fh:
            fh.write(md)
        with open(js_path, "w", encoding="utf-8") as fh:
            fh.write(js)
        entry = get_gcc_metadata(ticker)
        ps = provenance_summary(entry)
        summary_lines.append(
            f"- **{name}** (`{ticker}`) — tier1={ps['tier_1']} verified={ps['verified']} "
            f"missing={ps['missing']} · {md_path}"
        )
    with open(os.path.join(SAMPLE_DIR, "README.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(summary_lines) + "\n")
    print("\n".join(summary_lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
