"""
EisaX CIO Word Report Generator
Produces a styled .docx from markdown-formatted analysis content.
"""
import logging
import re
import uuid as _uuid_docx
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor, Cm, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
logger = logging.getLogger(__name__)


# ── Brand colors ───────────────────────────────────────────
NAVY   = RGBColor(0x0D, 0x1B, 0x2A)
GOLD   = RGBColor(0xC9, 0xA8, 0x4C)
GRAY   = RGBColor(0x6B, 0x72, 0x80)
WHITE  = RGBColor(0xFF, 0xFF, 0xFF)
GREEN  = RGBColor(0x16, 0xA3, 0x4A)
RED    = RGBColor(0xDC, 0x26, 0x26)
LIGHT  = RGBColor(0xF9, 0xFA, 0xFB)


def _set_cell_bg(cell, hex_color: str):
    """Set table cell background color."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'), hex_color)
    tcPr.append(shd)


def _add_run_bold(para, text: str, color: RGBColor = None, size: int = None):
    run = para.add_run(text)
    run.bold = True
    if color:
        run.font.color.rgb = color
    if size:
        run.font.size = Pt(size)
    return run


def clean_text(text: str) -> str:
    """Remove emojis and markdown symbols, keep Arabic + Latin."""
    import unicodedata
    cleaned = []
    for ch in text:
        cp = ord(ch)
        if 0x1F600 <= cp <= 0x1FAFF:
            continue
        if 0x2600 <= cp <= 0x27BF:
            continue
        cleaned.append(ch)
    return ''.join(cleaned).strip()


def _parse_inline(para, text: str, base_size: int = 10, base_color: RGBColor = None):
    """Parse **bold** and *italic* markdown inline into runs."""
    parts = re.split(r'(\*\*[^*]+\*\*|\*[^*]+\*)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = para.add_run(part[2:-2])
            run.bold = True
            run.font.size = Pt(base_size)
            if base_color:
                run.font.color.rgb = base_color
        elif part.startswith('*') and part.endswith('*'):
            run = para.add_run(part[1:-1])
            run.italic = True
            run.font.size = Pt(base_size)
            if base_color:
                run.font.color.rgb = base_color
        else:
            run = para.add_run(part)
            run.font.size = Pt(base_size)
            if base_color:
                run.font.color.rgb = base_color


def generate_cio_docx(content: str, out_path: str, ticker: str = "", title: str = "EisaX Report"):
    doc = Document()
    report_id = 'RPT-' + datetime.now().strftime('%Y%m%d') + '-' + _uuid_docx.uuid4().hex[:6].upper()

    # ── Page margins ───────────────────────────────────────
    for section in doc.sections:
        section.top_margin    = Cm(2.0)
        section.bottom_margin = Cm(2.0)
        section.left_margin   = Cm(2.5)
        section.right_margin  = Cm(2.5)
        footer = section.footer.paragraphs[0]
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer_run = footer.add_run(
            'DISCLAIMER: This report is generated by EisaX AI for informational purposes only. Not investment advice.'
        )
        footer_run.font.size = Pt(7)
        footer_run.font.color.rgb = GRAY

    # ── Header bar ─────────────────────────────────────────
    header_tbl = doc.add_table(rows=1, cols=2)
    header_tbl.style = 'Table Grid'
    lc = header_tbl.cell(0, 0)
    rc = header_tbl.cell(0, 1)
    _set_cell_bg(lc, '0D1B2A')
    _set_cell_bg(rc, '0D1B2A')

    lp = lc.paragraphs[0]
    lp.alignment = WD_ALIGN_PARAGRAPH.LEFT
    r = lp.add_run('EisaX')
    r.bold = True
    r.font.size = Pt(16)
    r.font.color.rgb = GOLD
    r2 = lp.add_run('  AI-Powered Investment Intelligence')
    r2.font.size = Pt(8)
    r2.font.color.rgb = WHITE

    rp = rc.paragraphs[0]
    rp.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    if ticker:
        rt = rp.add_run(f'INVESTMENT REPORT: {ticker}')
        rt.bold = True
        rt.font.size = Pt(10)
        rt.font.color.rgb = GOLD
        rp.add_run('\n')
    rd = rp.add_run(datetime.now().strftime('%B %d, %Y'))
    rd.font.size = Pt(8)
    rd.font.color.rgb = WHITE

    doc.add_paragraph()  # spacer
    header_para = doc.add_paragraph()
    header_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
    header_run = header_para.add_run('EisaX AI Intelligence Report')
    header_run.bold = True
    header_run.font.size = Pt(14)
    header_run.font.color.rgb = NAVY
    report_id_run = header_para.add_run(f'  Report ID: {report_id}')
    report_id_run.bold = True
    report_id_run.font.size = Pt(10)
    report_id_run.font.color.rgb = GRAY

    # ── Title block ────────────────────────────────────────
    tp = doc.add_paragraph()
    tp.alignment = WD_ALIGN_PARAGRAPH.LEFT
    tr = tp.add_run(ticker or title)
    tr.bold = True
    tr.font.size = Pt(28)
    tr.font.color.rgb = NAVY

    # Gold divider (via border)
    sp = doc.add_paragraph()
    sp.paragraph_format.space_after = Pt(4)
    pPr = sp._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '12')
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), 'C9A84C')
    pBdr.append(bottom)
    pPr.append(pBdr)

    doc.add_paragraph()  # spacer

    # ── Parse markdown content ─────────────────────────────
    lines = content.split('\n')
    skip_code = False
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # Code blocks — skip
        if stripped.startswith('```'):
            skip_code = not skip_code
            i += 1
            continue
        if skip_code:
            i += 1
            continue

        # Skip chart placeholders
        if 'eisax-chart' in stripped or 'data-ticker' in stripped:
            i += 1
            continue

        # ### Section header
        if stripped.startswith('###'):
            text = clean_text(stripped.lstrip('#').strip())
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(10)
            p.paragraph_format.space_after  = Pt(2)
            # Navy background via table
            tbl = doc.add_table(rows=1, cols=1)
            cell = tbl.cell(0, 0)
            _set_cell_bg(cell, '0D1B2A')
            cp = cell.paragraphs[0]
            cp.alignment = WD_ALIGN_PARAGRAPH.LEFT
            run = cp.add_run(text.upper())
            run.bold = True
            run.font.size = Pt(9)
            run.font.color.rgb = WHITE
            doc.add_paragraph()
            i += 1
            continue

        # ## Heading
        if stripped.startswith('##'):
            text = clean_text(stripped.lstrip('#').strip())
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(8)
            r = p.add_run(text)
            r.bold = True
            r.font.size = Pt(11)
            r.font.color.rgb = NAVY
            i += 1
            continue

        # # H1 — skip (already have ticker as title)
        if stripped.startswith('# '):
            i += 1
            continue

        # Markdown table
        if stripped.startswith('|') and '|' in stripped[1:]:
            table_lines = []
            while i < len(lines) and lines[i].strip().startswith('|'):
                table_lines.append(lines[i].strip())
                i += 1
            # Filter separator rows
            rows = []
            for tl in table_lines:
                if re.match(r'^\|[\s\-|:]+\|$', tl):
                    continue
                cells = [clean_text(c.strip()) for c in tl.split('|')[1:-1]]
                if any(cells):
                    rows.append(cells)
            if rows:
                ncols = max(len(r) for r in rows)
                for r in rows:
                    while len(r) < ncols:
                        r.append('')
                tbl = doc.add_table(rows=len(rows), cols=ncols)
                tbl.style = 'Table Grid'
                for ri, row in enumerate(rows):
                    for ci, cell_text in enumerate(row):
                        cell = tbl.cell(ri, ci)
                        cp = cell.paragraphs[0]
                        if ri == 0:
                            _set_cell_bg(cell, '0D1B2A')
                            run = cp.add_run(cell_text)
                            run.bold = True
                            run.font.size = Pt(8)
                            run.font.color.rgb = WHITE
                        else:
                            bg = 'F9FAFB' if ri % 2 == 0 else 'FFFFFF'
                            _set_cell_bg(cell, bg)
                            fc = NAVY
                            if cell_text in ('BUY', 'STRONG BUY'):
                                fc = GREEN
                            elif cell_text in ('SELL', 'STRONG SELL'):
                                fc = RED
                            run = cp.add_run(cell_text)
                            run.font.size = Pt(9)
                            run.font.color.rgb = fc
                doc.add_paragraph()
            continue

        # BUY/SELL/HOLD verdict box
        if re.search(r'\*\*(BUY|SELL|HOLD)', stripped):
            verdict = 'BUY' if 'BUY' in stripped else ('SELL' if 'SELL' in stripped else 'HOLD')
            bg = '16A34A' if verdict == 'BUY' else ('DC2626' if verdict == 'SELL' else 'C9A84C')
            tbl = doc.add_table(rows=1, cols=1)
            cell = tbl.cell(0, 0)
            _set_cell_bg(cell, bg)
            cp = cell.paragraphs[0]
            cp.alignment = WD_ALIGN_PARAGRAPH.CENTER
            text = clean_text(re.sub(r'\*\*([^*]+)\*\*', r'\1', stripped))
            run = cp.add_run(text)
            run.bold = True
            run.font.size = Pt(13)
            run.font.color.rgb = WHITE
            doc.add_paragraph()
            i += 1
            continue

        # Bullet point
        if stripped.startswith('- ') or stripped.startswith('* '):
            text = clean_text(stripped[2:])
            p = doc.add_paragraph(style='List Bullet')
            p.paragraph_format.left_indent = Cm(0.5)
            _parse_inline(p, text, base_size=10, base_color=RGBColor(0x37, 0x41, 0x51))
            i += 1
            continue

        # Numbered list
        if re.match(r'^\d+\.', stripped):
            text = clean_text(re.sub(r'^\d+\.\s*', '', stripped))
            p = doc.add_paragraph(style='List Number')
            _parse_inline(p, text, base_size=10, base_color=RGBColor(0x37, 0x41, 0x51))
            i += 1
            continue

        # Separator lines
        if re.match(r'^[-=*]{3,}$', stripped):
            i += 1
            continue

        # Regular paragraph
        text = clean_text(stripped)
        if text and len(text) > 2:
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(4)
            _parse_inline(p, text, base_size=10, base_color=RGBColor(0x37, 0x41, 0x51))
        i += 1

    # ── Disclaimer ─────────────────────────────────────────
    doc.add_paragraph()
    dp = doc.add_paragraph()
    pPr2 = dp._p.get_or_add_pPr()
    pBdr2 = OxmlElement('w:pBdr')
    top = OxmlElement('w:top')
    top.set(qn('w:val'), 'single')
    top.set(qn('w:sz'), '6')
    top.set(qn('w:space'), '1')
    top.set(qn('w:color'), 'C9A84C')
    pBdr2.append(top)
    pPr2.append(pBdr2)

    dr = dp.add_run(
        'DISCLAIMER: This report is generated by EisaX AI for informational purposes only. '
        'Not investment advice. Consult a qualified financial advisor. '
        'Powered by EisaX Intelligence | Eng. Ahmed Eisa'
    )
    dr.font.size = Pt(7)
    dr.font.color.rgb = GRAY

    doc.save(out_path)
    logger.debug(f"OK DOCX: {out_path}")
    return out_path, report_id
