"""
EisaX Export Engine - Multi-Format Document Generator
Supports: PDF, DOCX (Word), PPTX (PowerPoint), XLSX (Excel)
"""
import os
import re
import logging
from datetime import datetime
from typing import List, Dict

logger = logging.getLogger(__name__)

EXPORT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "static", "exports")
os.makedirs(EXPORT_DIR, exist_ok=True)


def _clean_text(text: str) -> str:
    """Remove markdown formatting for clean document text."""
    text = re.sub(r'```[\s\S]*?```', '[Code Block]', text)
    text = re.sub(r'`([^`]+)`', r'\1', text)
    text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)
    text = re.sub(r'\*([^*]+)\*', r'\1', text)
    text = re.sub(r'#{1,6}\s*', '', text)
    text = re.sub(r'!\[.*?\]\(.*?\)', '[Image]', text)
    text = re.sub(r'\[([^\]]+)\]\(.*?\)', r'\1', text)
    return text.strip()


def _timestamp():
    return datetime.now().strftime("%Y%m%d_%H%M%S")


# ─── PDF Export ────────────────────────────────────────────────────────────────
def export_pdf(messages: List[Dict], title: str = "EisaX Report") -> str:
    from core.playwright_pdf import html_to_pdf

    ts = datetime.now().strftime('%Y-%m-%d %H:%M')
    rows_html = ""
    for msg in messages:
        role = msg.get("role", "user")
        content = _clean_text(msg.get("content", "")).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        if role == "user":
            label, bg, color = "You", "#eef2ff", "#1e1b4b"
        else:
            label, bg, color = "EisaX", "#f0fdf4", "#14532d"
        rows_html += (
            f'<div style="margin-bottom:14px;padding:12px 16px;background:{bg};border-radius:8px;">'
            f'<div style="font-weight:700;font-size:10pt;color:{color};margin-bottom:4px">{label}</div>'
            f'<div style="font-size:10pt;color:#1a1a2e;white-space:pre-wrap">{content}</div>'
            f'</div>'
        )

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body{{font-family:Arial,sans-serif;font-size:10.5pt;color:#1a1a2e;margin:0;padding:0}}
  .header{{background:#4f46e5;color:#fff;padding:20px 30px;text-align:center}}
  .header h1{{margin:0;font-size:20pt}}
  .header p{{margin:4px 0 0;font-size:9pt;opacity:.8}}
  .body{{padding:24px 30px}}
  .footer{{margin-top:30px;text-align:center;font-size:8pt;color:#aaa;border-top:1px solid #eee;padding-top:10px}}
</style>
</head><body>
<div class="header"><h1>{title}</h1><p>Generated by EisaX | {ts}</p></div>
<div class="body">{rows_html}</div>
<div class="footer">EisaX AI - Powered by Eng. Ahmed Eisa</div>
</body></html>"""

    filename = f"EisaX_{_timestamp()}.pdf"
    filepath = os.path.join(EXPORT_DIR, filename)
    html_to_pdf(html, filepath)
    logger.info(f"PDF exported: {filepath}")
    return filename


# ─── DOCX (Word) Export ────────────────────────────────────────────────────────
def export_docx(messages: List[Dict], title: str = "EisaX Report") -> str:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Style the document
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title_para.runs:
        run.font.color.rgb = RGBColor(79, 70, 229)

    # Subtitle
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"Generated by EisaX | {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(128, 128, 128)

    doc.add_paragraph()  # Spacer

    for msg in messages:
        role = msg.get("role", "user")
        content = _clean_text(msg.get("content", ""))

        # Role heading
        role_para = doc.add_paragraph()
        role_run = role_para.add_run("You: " if role == "user" else "EisaX: ")
        role_run.bold = True
        role_run.font.size = Pt(11)
        if role != "user":
            role_run.font.color.rgb = RGBColor(79, 70, 229)

        # Content
        content_para = doc.add_paragraph(content)
        content_para.paragraph_format.space_after = Pt(8)

        # Divider
        divider = doc.add_paragraph()
        divider_run = divider.add_run("─" * 60)
        divider_run.font.size = Pt(6)
        divider_run.font.color.rgb = RGBColor(200, 200, 200)

    # Footer
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run("\nEisaX AI - Powered by Eng. Ahmed Eisa")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(150, 150, 150)
    run.italic = True

    filename = f"EisaX_{_timestamp()}.docx"
    filepath = os.path.join(EXPORT_DIR, filename)
    doc.save(filepath)
    logger.info(f"DOCX exported: {filepath}")
    return filename


# ─── PPTX (PowerPoint) Export ──────────────────────────────────────────────────
def export_pptx(messages: List[Dict], title: str = "EisaX Report") -> str:
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # ── Title Slide ──
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
    bg = slide.background.fill
    bg.solid()
    bg.fore_color.rgb = RGBColor(30, 27, 75)  # Dark indigo

    # Title text
    txBox = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(11), Inches(2))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(44)
    p.font.bold = True
    p.font.color.rgb = RGBColor(255, 255, 255)
    p.alignment = PP_ALIGN.CENTER

    # Subtitle
    p2 = tf.add_paragraph()
    p2.text = f"Generated by EisaX | {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    p2.font.size = Pt(18)
    p2.font.color.rgb = RGBColor(165, 160, 255)
    p2.alignment = PP_ALIGN.CENTER

    # ── Content Slides ──
    # Group messages into chunks of ~3 per slide
    chunk_size = 3
    for i in range(0, len(messages), chunk_size):
        chunk = messages[i:i + chunk_size]

        slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
        bg = slide.background.fill
        bg.solid()
        bg.fore_color.rgb = RGBColor(15, 23, 42)  # Slate-900

        y_pos = 0.5
        for msg in chunk:
            role = msg.get("role", "user")
            content = _clean_text(msg.get("content", ""))
            # Trim long content for slides
            if len(content) > 500:
                content = content[:497] + "..."

            txBox = slide.shapes.add_textbox(Inches(0.8), Inches(y_pos), Inches(11.5), Inches(0.4))
            tf = txBox.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.text = "You" if role == "user" else "EisaX"
            p.font.size = Pt(14)
            p.font.bold = True
            p.font.color.rgb = RGBColor(129, 140, 248) if role != "user" else RGBColor(250, 204, 21)

            y_pos += 0.4
            txBox2 = slide.shapes.add_textbox(Inches(0.8), Inches(y_pos), Inches(11.5), Inches(1.5))
            tf2 = txBox2.text_frame
            tf2.word_wrap = True
            p2 = tf2.paragraphs[0]
            p2.text = content
            p2.font.size = Pt(12)
            p2.font.color.rgb = RGBColor(226, 232, 240)

            y_pos += 2.0

    filename = f"EisaX_{_timestamp()}.pptx"
    filepath = os.path.join(EXPORT_DIR, filename)
    prs.save(filepath)
    logger.info(f"PPTX exported: {filepath}")
    return filename


# ─── XLSX (Excel) Export ───────────────────────────────────────────────────────
def export_xlsx(messages: List[Dict], title: str = "EisaX Report") -> str:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

    wb = Workbook()
    ws = wb.active
    ws.title = "EisaX Chat"

    # Column widths
    ws.column_dimensions['A'].width = 5
    ws.column_dimensions['B'].width = 12
    ws.column_dimensions['C'].width = 100
    ws.column_dimensions['D'].width = 20

    # Header styles
    header_fill = PatternFill(start_color="4F46E5", end_color="4F46E5", fill_type="solid")
    header_font = Font(name='Calibri', bold=True, color="FFFFFF", size=12)
    thin_border = Border(
        left=Side(style='thin', color='E5E7EB'),
        right=Side(style='thin', color='E5E7EB'),
        top=Side(style='thin', color='E5E7EB'),
        bottom=Side(style='thin', color='E5E7EB'),
    )

    # Title row
    ws.merge_cells('A1:D1')
    ws['A1'] = title
    ws['A1'].font = Font(name='Calibri', bold=True, size=16, color="4F46E5")
    ws['A1'].alignment = Alignment(horizontal='center')
    ws.row_dimensions[1].height = 35

    # Subtitle
    ws.merge_cells('A2:D2')
    ws['A2'] = f"Generated by EisaX | {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    ws['A2'].font = Font(name='Calibri', size=10, color="888888")
    ws['A2'].alignment = Alignment(horizontal='center')

    # Headers
    headers = ['#', 'Role', 'Content', 'Timestamp']
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=4, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = thin_border
    ws.row_dimensions[4].height = 28

    # Data rows
    user_fill = PatternFill(start_color="EEF2FF", end_color="EEF2FF", fill_type="solid")
    bot_fill = PatternFill(start_color="F0FDF4", end_color="F0FDF4", fill_type="solid")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    for idx, msg in enumerate(messages, 1):
        row = idx + 4
        role = msg.get("role", "user")
        content = _clean_text(msg.get("content", ""))
        fill = user_fill if role == "user" else bot_fill

        ws.cell(row=row, column=1, value=idx).border = thin_border
        ws.cell(row=row, column=1).alignment = Alignment(horizontal='center')
        ws.cell(row=row, column=1).fill = fill

        role_cell = ws.cell(row=row, column=2, value="You" if role == "user" else "EisaX")
        role_cell.font = Font(bold=True, color="4F46E5" if role != "user" else "000000")
        role_cell.border = thin_border
        role_cell.fill = fill
        role_cell.alignment = Alignment(horizontal='center')

        content_cell = ws.cell(row=row, column=3, value=content)
        content_cell.alignment = Alignment(wrap_text=True, vertical='top')
        content_cell.border = thin_border
        content_cell.fill = fill

        ts_cell = ws.cell(row=row, column=4, value=timestamp)
        ts_cell.border = thin_border
        ts_cell.fill = fill
        ts_cell.alignment = Alignment(horizontal='center')

        # Auto-height for long content
        ws.row_dimensions[row].height = max(20, min(200, len(content) * 0.3))

    filename = f"EisaX_{_timestamp()}.xlsx"
    filepath = os.path.join(EXPORT_DIR, filename)
    wb.save(filepath)
    logger.info(f"XLSX exported: {filepath}")
    return filename


# ─── Main Export Handler ───────────────────────────────────────────────────────
def export(format: str, messages: List[Dict], title: str = "EisaX Report") -> Dict:
    """
    Main export function. Returns dict with success, filename, download_url.
    format: 'pdf' | 'docx' | 'pptx' | 'xlsx'
    """
    try:
        exporters = {
            "pdf": export_pdf,
            "docx": export_docx,
            "pptx": export_pptx,
            "xlsx": export_xlsx,
        }

        if format not in exporters:
            return {"success": False, "error": f"Unsupported format: {format}. Use: pdf, docx, pptx, xlsx"}

        filename = exporters[format](messages, title)
        return {
            "success": True,
            "filename": filename,
            "download_url": f"/v1/download/{filename}"
        }
    except Exception as e:
        logger.error(f"Export failed ({format}): {e}")
        return {"success": False, "error": str(e)}
